export interface AdkAgentRegistrationPayload {
  name: string; // User-defined alias for OAP
  a2aBaseUrl: string;
  authentication?: { type: 'apikey' | 'bearer'; token?: string };
}

export interface AdkAgentStoredData {
  id: string; // UUID generated by OAP
  name: string;
  a2aBaseUrl: string;
  authentication?: { type: 'apikey' | 'bearer'; encryptedToken?: string };
  agentCard: any; // Store the fetched Agent Card JSON object
  createdAt: string; // ISO date string
  updatedAt: string; // ISO date string
}

export interface AgentCard {
  name: string;
  description?: string;
  url: string; // This is the A2A service endpoint from the card
  capabilities?: { streaming?: boolean; pushNotifications?: boolean };
  skills?: Array<{ id: string; name: string; description?: string }>;
}
